# Generated by Django 4.2.21 on 2025-07-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productingredient_price'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitemingredient',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='orderitemingredient',
            name='group_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Grupo do Produto'),
        ),
        migrations.AlterUniqueTogether(
            name='orderitemingredient',
            unique_together={('order_item', 'ingredient', 'group_name')},
        ),
    ]
