# Generated by Django 4.2.21 on 2025-07-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productingredient_price'),
        ('orders', '0002_alter_orderitemingredient_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitemingredient',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='orderitemingredient',
            name='is_extra',
            field=models.BooleanField(default=False, verbose_name='É Extra'),
        ),
        migrations.AlterUniqueTogether(
            name='orderitemingredient',
            unique_together={('order_item', 'ingredient', 'group_name', 'is_extra')},
        ),
    ]
