# Generated by Django 4.2.10 on 2025-08-03 01:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_alter_orderitemingredient_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_number",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Número do Pedido"
            ),
        ),
    ]
