# Generated by Django 4.2.10 on 2025-08-21 22:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_order_order_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, verbose_name="Número do Pedido"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendente"),
                    ("confirmed", "Confirmado"),
                    ("preparing", "Preparando"),
                    ("ready", "Pronto"),
                    ("delivered", "Entregue"),
                    ("cancelled", "Cancelado"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["restaurant", "created_at"],
                name="orders_orde_restaur_763bf4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["status", "created_at"], name="orders_orde_status_25e057_idx"
            ),
        ),
    ]
