# Generated by Django 4.2.10 on 2025-07-24 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='emoji',
            field=models.CharField(blank=True, default='', max_length=2, verbose_name='Emoji'),
        ),
    ]
