# Generated by Django 4.2.21 on 2025-07-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='is_extra',
            field=models.BooleanField(default=False, verbose_name='É Extra'),
        ),
        migrations.AddField(
            model_name='ingredientcategory',
            name='is_extra',
            field=models.BooleanField(default=False, verbose_name='É Extra'),
        ),
    ]
