# Generated by Django 4.2.21 on 2025-07-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_ingredient_is_extra_ingredientcategory_is_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='productingredient',
            name='is_extra',
            field=models.BooleanField(default=False, verbose_name='É Extra'),
        ),
    ]
