# Generated by Django 4.2.21 on 2025-07-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productingredient_is_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='productingredient',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço Extra'),
        ),
    ]
